name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: Package version (e.g. v0.1.0)
        required: false

env:
  GHCR_REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install up
        uses: upbound/action-up@53fe6395637d884c80d2bbc8c2d75d0ece776ced # v1
        with:
          skip-login: true

      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push server image
        run: make all ${{ inputs.version && format('IMAGE_TAG={0}', inputs.version) || '' }}

      - name: Build and Push project
        uses: upbound/action-up-project@b849ec1eb303ae4abf22b2b86c0e2afca155137b # v1
        with:
          push-project: true
          tag: ${{ inputs.version || '' }}
          skip-login-check: true
